# Generated by Django 5.1.2 on 2025-03-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='prizz_name',
            new_name='pizza_name',
        ),
    ]
